# Generated by Django 4.0.4 on 2022-04-30 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_info', models.CharField(max_length=200)),
                ('created_date', models.DateTimeField(verbose_name='date created')),
            ],
        ),
    ]
