# Generated by Django 4.0.4 on 2022-05-02 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todolist', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='task_status',
            field=models.BooleanField(default=False),
        ),
    ]
